# Generated by Django 5.0.3 on 2024-05-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comments_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
